### ISSUE TITLE
ScraperAPI not working and couple of errors in code

### ISSUE THREAD

**Issue by rokopi-byte** [enzodesena/scopus-checker#2]
Hi @enzodesena ,
I was looking for a project like this and found this great repo! I want to contribuite..
First of all I've found couple of errors that prevent its use:

1)
scopus-checker.py -> line 28, missing colon

2)
comparator.py 

In load_documents, that is used for both documents and citations CSV files, row['References'] is used, but since there is no such field in documents CSV, an error is raised. I used this workaround:

row['References'].split('; ') if 'References' in row else [],

Even like this, I was unable to correctly run the software, using ScraperAPI I got this errors:

```
Traceback (most recent call last):
  File "/home/rocco/repo/scopus-checker/scopus-checker/scopus-checker.py", line 137, in <module>
    set_up_proxy(use_proxy, scraperapi_key)
  File "/home/rocco/repo/scopus-checker/scopus-checker/scopus-checker.py", line 76, in set_up_proxy
    scholarly.use_proxy(pg)
  File "/home/rocco/repo/scopus-checker/scopus-checker/.venv/lib/python3.9/site-packages/scholarly/_scholarly.py", line 65, in use_proxy
    self.__nav.use_proxy(proxy_generator, secondary_proxy_generator)
  File "/home/rocco/repo/scopus-checker/scopus-checker/.venv/lib/python3.9/site-packages/scholarly/_navigator.py", line 67, in use_proxy
    proxy_works = self.pm2.FreeProxies()
  File "/home/rocco/repo/scopus-checker/scopus-checker/.venv/lib/python3.9/site-packages/scholarly/_proxy_generator.py", line 510, in FreeProxies
    proxy = self._proxy_gen(None)  # prime the generator
StopIteration
```

If I use a free proxy, just hangs after the first document..
Thanks

**Comment by enzodesena** [comment]
Hi Rocco, thanks a lot! Glad it was useful. 
Your suggestions look good. If you create a pull request I will accept it. 

PS: apologies for the long delay.

**Comment by enzodesena** [comment]
Hi @roccopietrini . On second thought, I did make those changes and pushed. (Not really sure how I missed those before!). Still, if you'd like to be a contributor officially, please do let me know.
